[build]
builder = "nixpacks"
buildCommand = "npm install --include=optional && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_22"]

[deploy]
startCommand = "npx serve dist -p $PORT"
